// <auto-generated />
using System;
using AsmShare.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AsmAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220807092855_asm6")]
    partial class asm6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AsmShare.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("ChiTietDonHang_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DonHang_Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<float>("MonAn_Gia")
                        .HasColumnType("real");

                    b.Property<int>("MonAn_Id")
                        .HasColumnType("int");

                    b.Property<string>("MonAn_Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MonAn_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MonAn_SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("VAT")
                        .HasColumnType("int");

                    b.HasKey("ChiTietDonHang_Id");

                    b.HasIndex("DonHang_Id");

                    b.HasIndex("MonAn_Id");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("AsmShare.Models.DonHang", b =>
                {
                    b.Property<int>("DonHang_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("GiaTienChuaVAT")
                        .HasColumnType("real");

                    b.Property<float>("GiaTienDaVAT")
                        .HasColumnType("real");

                    b.Property<int>("HoaDon_TrangThai")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("KhachHang_DiaChi")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KhachHang_Email")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("KhachHang_Id")
                        .HasColumnType("int");

                    b.Property<string>("KhachHang_Name")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KhachHang_SoDienThoai")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<float>("VAT")
                        .HasColumnType("real");

                    b.HasKey("DonHang_Id");

                    b.HasIndex("KhachHang_Id");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("AsmShare.Models.KhachHang", b =>
                {
                    b.Property<int>("KhachHang_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KhachHang_Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KhachHang_Mota")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("KhachHang_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("KhachHang_NgaySinh")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("KhachHang_PassWord")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KhachHang_PassWord2")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KhachHang_Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("KhachHang_Id");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("AsmShare.Models.MonAn", b =>
                {
                    b.Property<int>("MonAn_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("MonAn_DanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("MonAn_GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<float>("MonAn_Gia")
                        .HasColumnType("real");

                    b.Property<string>("MonAn_Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonAn_MoTa")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MonAn_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MonAn_NgaySua")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("MonAn_NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.Property<float>("VAT")
                        .HasColumnType("real");

                    b.HasKey("MonAn_Id");

                    b.ToTable("MonAns");
                });

            modelBuilder.Entity("AsmShare.Models.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDung_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("Locked")
                        .HasColumnType("bit");

                    b.Property<string>("NguoiDung_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiDung_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiDung_NgaySinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NguoiDung_PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NguoiDung_PassWord2")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NguoiDung_SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NguoiDung_UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NguoiDung_Id");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("AsmShare.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("AsmShare.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("DonHang_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AsmShare.Models.MonAn", "MonAn")
                        .WithMany("ChiTietDonHang")
                        .HasForeignKey("MonAn_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("AsmShare.Models.DonHang", b =>
                {
                    b.HasOne("AsmShare.Models.KhachHang", "KhachHang")
                        .WithMany("DonHang")
                        .HasForeignKey("KhachHang_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("AsmShare.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("AsmShare.Models.KhachHang", b =>
                {
                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("AsmShare.Models.MonAn", b =>
                {
                    b.Navigation("ChiTietDonHang");
                });
#pragma warning restore 612, 618
        }
    }
}
